### ISSUE TITLE
question/doc-request: what is meant by "handle" in "handle RSS and ATOM feeds"

### ISSUE THREAD

**Issue by jzacsh** [sergeche/xmlview#56]
the following checkbox:
> Intercept requests for XML, RSS and ATOM documents

has this warning:
> WARNING! With this option enabled, Chrome won’t be able to handle RSS and ATOM feeds.

What is this referring to? What does Chrome do with RSS/ATOM feeds that this would disable? _(and mind if I send you a pull request to update that warning with a "learn more" link w/whatever the answer is?)_

**Comment by sergeche** [comment]
Some people want to use XMLView to view RSS and ATOM feeds (instead of default behaviour).

**Comment by jzacsh** [comment]
Ah, okay! I thought it was implying something about some native behavior Chrome has when it detects these content-types. Thanks!
