### ISSUE TITLE
Display (toggle) Line numbers

### ISSUE THREAD

**Issue by skumargithub** [sergeche/xmlview#57]
It does not appear that it's possible to view line numbers in an xml document.

If it's not already there, I am willing to volunteer to do submit a PR.

**Comment by sergeche** [comment]
No, there’s no such feature in plans, feel free to create a PR

**Comment by skumargithub** [comment]
Any suggestions on how to implement it?

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 27, 2017 at 2:41 PM, Sergey Chikuyonok<notifications@github.com> wrote:   
Closed #57.

**Comment by sergeche** [comment]
I guess it will require custom XML parser that can store node’s location in source code

**Comment by skumargithub** [comment]
Thanks, I will try to give it a shot.
Will ping if I need help.

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 27, 2017 at 2:51 PM, Sergey Chikuyonok<notifications@github.com> wrote:   
I guess it will require custom XML parser that can store node’s location in source code
