### ISSUE TITLE
Monetization?

### ISSUE THREAD

**Issue by tsimmons** [sergeche/xmlview#62]
Just saw the latest commit. Can you please transparently explain what the deal was? Thanks.

**Comment by sergeche** [comment]
A company suggested to add a script which should ”silently” add some context ads when used searches some goods. In practice, it was implemented so badly and tried to inject script on every page user visits (including localhost) which caused lots of sudden errors in DevTools console.

I had no intention to spy on someone or steal sensitive data, just tried to make some profit from existing extension, as company suggested :)

**Comment by tsimmons** [comment]
Gotcha. Thanks for your transparency.
