### ISSUE TITLE
Mouse scrolling doesn't work

### ISSUE THREAD

**Issue by DanAtkinson** [sergeche/xmlview#65]
**Steps to reproduce:**
1. Open an XML page that goes beyond the fold (eg is longer than the browser can show).
2. Attempt to scroll the document or the outline in the side-pane using your mouse wheel.

**What I expect to happen:**
Document or outline (depending on which is focused) should scroll in accordance with my OS preferences.

**What actually happens:**
Nothing. It's as if the scrolling is not recognised.

**Anything else:**
Using Chrome 66.0.3359.117 on Windows 10.

**Comment by pdavis8** [comment]
Same issue for me as well.
Also using Chrome Version 66.0.3359.117 on High Sierra

**Comment by sergeche** [comment]
Thanks, will check it out

**Comment by karlbuckland** [comment]
I have the issue also (Chrome 66.0.3359.181 Windows 10).

It is reproducible here: https://www.w3schools.com/xml/plant_catalog.xml

**Comment by chadokruse** [comment]
It appears disabling threaded scrolling fixes the issue, at least on Chrome 66.0.3359.181 / macOS 10.13.4

chrome://flags/#disable-threaded-scrolling

**Comment by dirkgiese** [comment]
for me the problem stand in console "// listen to signals"
processing unknown type: 10
2xv.js:3509 is prevented? false

perhaps it helps

**Comment by pstatonvt** [comment]
@chadokruse this is the fix that worked for me, thank you!

**Comment by sjfarrar** [comment]
I've been having this issue also and I was also able to reproduce it with the plant_catalog.xml file supplied above.

I'm on Chrome Version 67.0.3396.99 (Official Build) (64-bit) on Mac OS 10.13.5

I checked the property mentioned by @chadokruse and changing that to disabled indeed solved the problem. I've set it back to enabled since this is the only extension I use that seems to have this issue. @sergeche did you happen to have this property turned on?

Hopefully this one gets solved soon :)

**Comment by qmacro** [comment]
FWIW I have this issue too. I much prefer this XML viewer to others, except this scrolling issue makes it a non-starter for me. The workaround suggested by @chadokruse works, but like @sjfarrar I'm uneasy about hacking something in the browser just to make this one extension work. Good luck with solving it (this would be beyond me) and thanks for the work so far!

**Comment by sergeche** [comment]
Still can’t reproduce 😬 Tested on Chrome Version 67.0.3396.99 (Official Build) (64-bit) on both macOS 10.13.5 and Windows 10 with both threaded scrolling enabled and disabled. Maybe someone can give me TeamViewer access to his computer so I can play around with extension settings?

**Comment by DanAtkinson** [comment]
I am happy to close this now. I believe the issue has been resolve by previous updates.

Since I opened this issue, my computer died, and switching to a new one has meant that I no longer have this issue (even without touching the Chrome flags.

Thanks, Dan

**Comment by tsimmons** [comment]
Still happening for me; Disabled all other extensions to no avail; Disabling thread-scrolling fixes it as well for me but will probably not leave it that way. Running macOS 10.12.6 running 67.0.3396.99 (Official Build) (64-bit).
